### ISSUE TITLE
Mui v5

### ISSUE THREAD

**Issue by gvlatko** [tran-simon/material-duration-picker#2]
Any chance there will be support for v5?

Getting an error trying to compile.

Module not found: Error: Can't resolve '@material-ui/core' 

Which makes sense since @material-ui/core has been moved to @mui/material.

Thanks!

**Comment by tran-simon** [comment]
I can't directly support v5 https://stackoverflow.com/questions/70217864/how-to-create-a-package-for-a-react-component-that-supports-material-ui-versions?noredirect=1#comment124127105_70217864

I deployed a version on npm that supports mui v5: https://www.npmjs.com/package/material-duration-picker/v/1.4.5-muiv5

Install it using

```
npm i material-duration-picker@1.4.5-muiv5
```

I have not tested it myself, so their might be some ui bugs from the migration to mui v5. Let me know if you find any!
